FROM sonarqube:8.9-community
EXPOSE 9000
COPY . .
VOLUME ["c:\volumes\sonarqube:/opt/sonarqube/data"]
VOLUME ["c:\volumes\sonarqube:/opt/sonarqube/logs"]
VOLUME ["c:\volumes\sonarqube:/opt/sonarqube/extensions"]

