version: '3'

networks:
  redis_network:
    driver: bridge

services:
  redis:
    container_name: redis
    hostname: redis
    image: redis
    networks:
      - redis_network
    ports:
      - "6379:6379"

  redis_commander:
    image: rediscommander/redis-commander:latest
    hostname: redis-commander
    container_name: redis_commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: ${REDIS_HOSTS}
    ports:
      - 8081:8081
    depends_on:
      - redis
    networks:
      - redis_network  
