version: '3'

networks:
  postgres-compose-network:
    driver: bridge

services:
  postgres-compose:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "senha123"
    volumes:
      - c:\volumes\postgres:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
    ports:
      - "15432:5432"

  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
       PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
       PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - postgres-compose-network
    ports:
      - "16543:80"
    depends_on:
      -  postgres-compose
  

